### ISSUE TITLE
An error occured while logging

### ISSUE THREAD

**Issue by ArabicCat** [ICEGXG/UntitledNuker#3]
An error occured while logging:
Traceback (most recent call last):
  File "c:\Users\nee\3D Objects\gangsta\main.py", line 617, in <module>
    bot.run(token, bot=not userOrBot())
TypeError: Client.run() got an unexpected keyword argument 'bot'

**Comment by ICEGXG** [comment]
I already know about this issue, and will fix it soon
Now you can just remove `bot=not userOrBot()` part, and it should work
